### ISSUE TITLE
Data splitting error

### ISSUE THREAD

**Issue by ghost** [Muhammad-MujtabaSaeed/Caltech-Birds-Classification#2]
CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0001_796111.jpg
y
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-42-5bba2d71d8a7> in <module>()
      6         print(folder)
      7         print('y')
----> 8         img_name = train_dataset.imgs[j][0][9:].split('\\')[1]
      9         io.imsave('./test/'+folder+'/'+img_name,img)
     10         os.remove(path)

IndexError: list index out of range

**Comment by Stephenfang51** [comment]
> ## CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0001_796111.jpg
> y
> IndexError Traceback (most recent call last)
> in ()
> 6 print(folder)
> 7 print('y')
> ----> 8 img_name = train_dataset.imgs[j][0][9:].split('\')[1]
> 9 io.imsave('./test/'+folder+'/'+img_name,img)
> 10 os.remove(path)
> 
> IndexError: list index out of range

Sir, I think the problem might be the `split("\")`
It supposed to be `split("/")`

you could check `train_dataset.imgs[j][0][20:]` Out
if it shows `'001.Black_footed_Albatross/Black_Footed_Albatross_0001_796111.jpg'`
You will know how to do !

Thanks :)
